apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: {{ .value.service.type }}
  selector:
      purpose: helm-demo
        # purpose: headless-svc-demo
      project: roboshop
  ports:
    - protocol: TCP
      port: {{ .value.service.seviceport }} # service port
      targetPort: 80 #container port